Repository fac20/WEEK-2-CIKP-, pull requests merged in 2020-07, with the labels that each got.

#13 HTML Skeleton
  Index.css
  ferrellDad.gif
  gif-joke-page.html
  index.html
  randomLogo.jpg
Labels: Core Stories

#26 Ephie final changes
  .DS_Store
  Index.css
  gif-joke-page.html
  images/.DS_Store
  images/blue logo .png
  images/randomLogo.jpg
  images/stan-dad.png
  index.html
Labels: Design, Stretch Goal, User Story

#32 Slick readme
  README.md
Labels: Acceptance Criteria, documentation
